# Compression configuration for experience data storage

# Default compression settings for all fields unless overridden
default:
  format: zstd  # Options: none, zstd, gzip, lz4
  level: 3     # Compression level (0-9), 0 = no compression

# Field-specific compression settings
fields:
  # For large but important observation data, use high compression
  observations:
    format: zstd
    level: 7
  
  # For smaller numerical data, use faster compression
  rewards:
    format: lz4
    level: 1
  
  # For binary action data, use a balance of speed and compression
  actions:
    format: zstd
    level: 3
  
  # For masks or other binary data
  masks:
    format: gzip
    level: 5
  
  # For fields that need fast access but less important for storage
  metadata:
    format: lz4
    level: 1
  
  # For fields that should not be compressed
  timestamps:
    format: none
    level: 0

# Storage-specific settings
storage:
  chunk_size: 1000  # Size of chunks for HDF5 storage