## Default SAT solver configuration
##
## This file defines configuration parameters for the unified SAT solver interface.

# Solver configuration
solver:
  # Default solver to use
  name: walksat
  
  # General solver parameters
  timeout: 30.0
  max_iterations: 100000
  max_tries: 10
  
  # WalkSAT specific parameters
  walksat:
    random_probability: 0.5
    max_flips: 50000
  
  # PySAT-based solver parameters (if available)
  cdcl:
    use_timer: true
    incremental: true
    reduce_limit: 100

# Problem parameters
problem:
  num_vars: 20
  num_clauses: 85
  clause_size: 3
  seed: 42

# Logging configuration
logging:
  level: INFO
  file: logs/solver.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Experiment configuration
experiment:
  name: default
  runs: 5
  save_results: true
  results_dir: ./results
  
  # Plotting parameters
  plot:
    show: true
    format: png
    dpi: 300